# This is a basic workflow to help you get started with Actions

name: US1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t mealplan:staging .

      - name: Run Tests
        run: |
          echo "Running tests..."
          # Replace with your actual test command, e.g. pytest, npm test, etc.
          echo "Tests passed!"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Staging
        run: |
          echo "Stopping old containers..."
          docker compose down || true
          echo "Starting new containers..."
          docker compose up -d --force-recreate
          echo "Deployment finished"
          docker logs webserver > deployment.log

      - name: Upload Deployment Logs
        uses: actions/upload-artifact@v4
        with:
          name: deployment-logs
          path: deployment.log
